export const GameStages = {
  INIT: "INIT",
  DISTRIBUTE_CARDS: "DISTRIBUTE_CARDS",
  BIDDING: "BIDDING",
  BIDDING_COMPLETE: "BIDDING_COMPLETE",
  TRUMP_SELECTION: "TRUMP_SELECTION",
  TRUMP_SELECTION_COMPLETE: "TRUMP_SELECTION_COMPLETE",
  PLAYING: "PLAYING",
  CARDS_DISPLAY: "CARDS_DISPLAY",
  TRICK_COMPLETE: "TRICK_COMPLETE",
  TRICK_SUMMARY: "TRICK_SUMMARY",
  GAME_OVER: "GAME_OVER",
} as const;

export type GameStage = (typeof GameStages)[keyof typeof GameStages];
